name: flutter_map_marker_cluster_plus
description: Updated library based on flutter map v8 from fork of flutter_map_marker_cluster, Provides beautiful animated marker clustering functionality for flutter_map.
version: 1.4.2

homepage: https://github.com/prakashbahadurchand/flutter_map_marker_cluster_plus

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^8.1.1
  flutter_map_marker_popup_plus: ^7.1.0
  latlong2: ^0.9.1

dependency_overrides:
    flutter_map: ^8.1.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
